ALTER TABLE Orders DROP CONSTRAINT FK_Orders_CUSTOMER_ID
ALTER TABLE OrderLines DROP CONSTRAINT FK_OrderLines_ORDER_ID
DROP TABLE Orders
DROP TABLE OrderLines
DROP TABLE Customers
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
