ALTER TABLE Orders DROP CONSTRAINT FK_Orders_CUSTOMER_ID
ALTER TABLE OrderLines DROP CONSTRAINT FK_OrderLines_ORDER_ID
DROP TABLE Orders
DROP TABLE OrderLines
DROP TABLE Customers
DROP SEQUENCE SEQ_GEN_SEQUENCE
